name: Feature Check (Common)
on:
  pull_request:
    branches: [ develop ]

env:
  KEYSTORE: ${{ secrets.KEYSTORE }}
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

jobs:
  lintBuildTest:
    name: Lint, Build, and Test App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout project
        with:
          token: ${{ secrets.PR_TOKEN }}

      - name: Setup Secrets
        run: |
          echo '${{ secrets.COMMON_SHARED_SECRETS }}' >> shared/common/secrets.properties
          echo '${{ secrets.PH_SHARED_SECRETS }}' >> shared/philippines/secrets.properties
          echo '${{ secrets.VN_SHARED_SECRETS }}' >> shared/vietnam/secrets.properties

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # Lint, Build, and Test on Changed Gradle Modules
      - name: Run lint, build, and test
        shell: bash
        run: |
          CURRENT_BRANCH=origin/${{ github.head_ref }}
          BASE_BRANCH=origin/${{ github.base_ref }}
          scripts/sanitize.changed.modules.sh $CURRENT_BRANCH $BASE_BRANCH

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v2
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Commit Files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_options: '-S'
          commit_message: '[CI] Applies formatting fixes'
          commit_user_name: Kurt Renzo Acosta
          commit_user_email: 18444033+kuuuurt@users.noreply.github.com
          commit_author: Kurt Renzo Acosta <18444033+kuuuurt@users.noreply.github.com>

      - name: Clean-up Secrets
        run: |
          rm -rf shared/common/secrets.properties
          rm -rf shared/philippines/secrets.properties
          rm -rf shared/vietnam/secrets.properties
